
stages:
  - wake
  - buildWindows
  - buildLinux
  - buildOsx
  - testWindows
  - testLinux
  - testOsx

wake:
  stage: wake
  tags:
    - ubuntu
  script:
    - wakeonlan 10:9A:DD:51:F5:11
    - wakeonlan 70:85:C2:59:37:97
    - sleep 1m

buildWindows:
  stage: buildWindows
  tags:
    - windows
  script:
    - gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

buildLinux:
  stage: buildLinux
  tags:
    - ubuntu
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

buildOsx:
  stage: buildOsx
  tags:
    - osx
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

testWindows:
  stage: testWindows
  script:
    - gradlew check

testLinux:
  stage: testLinux
  script:
    - ./gradlew check

testOsx:
  stage: testOsx
  script:
    - ./gradlew check

after_script:
  - echo "End CI"
