
stages:
  - wake
  - buildLinux
  - buildOsx
  - testLinux
  - testOsx

wake:
  stage: wake
  tags:
    - ubuntu
  script:
    - wakeonlan 10:9A:DD:51:F5:11
    - sleep 1m


buildLinux:
  stage: buildLinux
  tags:
    - ubuntu
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

buildOsx:
  stage: buildOsx
  tags:
    - osx
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

testLinux:
  stage: testLinux
  script:
    - ./gradlew check

testOsx:
  stage: testOsx
  script:
    - ./gradlew check

after_script:
  - echo "End CI"
