#before_script:
#  - eval $(ssh-agent -s)
#  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
#  - mkdir -p ~/.ssh
#  - chmod 700 ~/.ssh
#  - git clone git@gitlab.nimblygames.com:NimblyGames/core.git

stages:
  - publish

publishWindows:
  stage: publish
  tags:
    - windows
  script:
    - ./gradlew -i --no-build-cache clean build SteamSdkJni-windows:publish

publishLinux:
  stage: publish
  tags:
    - ubuntu
  script:
    - ./gradlew -i --no-build-cache clean build publish

publishOsx:
  stage: publish
  tags:
    - osx
  script:
    - ./gradlew -i --no-build-cache clean build SteamSdkJni-macos:publish

after_script:
  - echo "End CI"
