
stages:
  - wake
  - build
  - wake
  - test

wake:
  stage: wake
  tags:
    - ubuntu
  script:
    - wakeonlan 10:9A:DD:51:F5:11
    - wakeonlan 70:85:C2:59:37:97
    - sleep 1m

buildWindows:
  stage: build
  tags:
    - windows
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

buildLinux:
  stage: build
  tags:
    - ubuntu
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

buildOsx:
  stage: build
  tags:
    - osx
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

testWindows:
  stage: test
  script:
    - ./gradlew check

testLinux:
  stage: test
  script:
    - ./gradlew check

testOsx:
  stage: test
  script:
    - ./gradlew check

after_script:
  - echo "End CI"
