/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class steam_ISteamApps */

#ifndef _Included_steam_ISteamApps
#define _Included_steam_ISteamApps
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     steam_ISteamApps
 * Method:    nBIsSubscribed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamApps_nBIsSubscribed
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamApps
 * Method:    nBIsLowViolence
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamApps_nBIsLowViolence
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamApps
 * Method:    nBIsCyberCafe
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamApps_nBIsCyberCafe
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamApps
 * Method:    nBIsVACBanned
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamApps_nBIsVACBanned
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamApps
 * Method:    nGetCurrentGameLanguage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_steam_ISteamApps_nGetCurrentGameLanguage
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamApps
 * Method:    nGetAvailableGameLanguages
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_steam_ISteamApps_nGetAvailableGameLanguages
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamApps
 * Method:    nBIsSubscribedApp
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamApps_nBIsSubscribedApp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     steam_ISteamApps
 * Method:    nBIsDlcInstalled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamApps_nBIsDlcInstalled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     steam_ISteamApps
 * Method:    nGetEarliestPurchaseUnixTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_steam_ISteamApps_nGetEarliestPurchaseUnixTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     steam_ISteamApps
 * Method:    nBIsSubscribedFromFreeWeekend
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamApps_nBIsSubscribedFromFreeWeekend
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamApps
 * Method:    nGetDLCCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_steam_ISteamApps_nGetDLCCount
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamApps
 * Method:    nGetDLCDataByIndex
 * Signature: (ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_steam_ISteamApps_nGetDLCDataByIndex
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     steam_ISteamApps
 * Method:    nInstallDLC
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_steam_ISteamApps_nInstallDLC
  (JNIEnv *, jclass, jlong);

/*
 * Class:     steam_ISteamApps
 * Method:    nUninstallDLC
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_steam_ISteamApps_nUninstallDLC
  (JNIEnv *, jclass, jlong);

/*
 * Class:     steam_ISteamApps
 * Method:    nGetCurrentBetaName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_steam_ISteamApps_nGetCurrentBetaName
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamApps
 * Method:    nMarkContentCorrupt
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamApps_nMarkContentCorrupt
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     steam_ISteamApps
 * Method:    nGetInstalledDepots
 * Signature: (JLjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_steam_ISteamApps_nGetInstalledDepots
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     steam_ISteamApps
 * Method:    nGetAppInstallDir
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_steam_ISteamApps_nGetAppInstallDir
  (JNIEnv *, jclass, jlong);

/*
 * Class:     steam_ISteamApps
 * Method:    nBIsAppInstalled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamApps_nBIsAppInstalled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     steam_ISteamApps
 * Method:    nGetAppOwner
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_steam_ISteamApps_nGetAppOwner
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamApps
 * Method:    nGetAppBuildId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_steam_ISteamApps_nGetAppBuildId
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
