/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class steam_ISteamFriends */

#ifndef _Included_steam_ISteamFriends
#define _Included_steam_ISteamFriends
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     steam_ISteamFriends
 * Method:    nGetPersonaName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_steam_ISteamFriends_nGetPersonaName
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamFriends
 * Method:    nGetFriendCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_steam_ISteamFriends_nGetFriendCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     steam_ISteamFriends
 * Method:    nGetFriendByIndex
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_steam_ISteamFriends_nGetFriendByIndex
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     steam_ISteamFriends
 * Method:    nGetFriendPersonaName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_steam_ISteamFriends_nGetFriendPersonaName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     steam_ISteamFriends
 * Method:    nGetClanCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_steam_ISteamFriends_nGetClanCount
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamFriends
 * Method:    nGetClanByIndex
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_steam_ISteamFriends_nGetClanByIndex
  (JNIEnv *, jclass, jint);

/*
 * Class:     steam_ISteamFriends
 * Method:    nGetClanName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_steam_ISteamFriends_nGetClanName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     steam_ISteamFriends
 * Method:    nGetSmallFriendAvatar
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_steam_ISteamFriends_nGetSmallFriendAvatar
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
