/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class steam_ISteamUser */

#ifndef _Included_steam_ISteamUser
#define _Included_steam_ISteamUser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     steam_ISteamUser
 * Method:    nGetSteamID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_steam_ISteamUser_nGetSteamID
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamUser
 * Method:    nInitiateGameConnection
 * Signature: (Ljava/nio/ByteBuffer;JIIZ)I
 */
JNIEXPORT jint JNICALL Java_steam_ISteamUser_nInitiateGameConnection
  (JNIEnv *, jclass, jobject, jlong, jint, jint, jboolean);

/*
 * Class:     steam_ISteamUser
 * Method:    TerminateGameConnection
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_steam_ISteamUser_TerminateGameConnection
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
