/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class steam_ISteamGameServer */

#ifndef _Included_steam_ISteamGameServer
#define _Included_steam_ISteamGameServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     steam_ISteamGameServer
 * Method:    LogOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_steam_ISteamGameServer_LogOn
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamGameServer
 * Method:    LogOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_steam_ISteamGameServer_LogOff
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamGameServer
 * Method:    BLoggedOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamGameServer_BLoggedOn
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamGameServer
 * Method:    BSecure
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamGameServer_BSecure
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamGameServer
 * Method:    GetPublicIP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_steam_ISteamGameServer_GetPublicIP
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamGameServer
 * Method:    nGetSteamID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_steam_ISteamGameServer_nGetSteamID
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamGameServer
 * Method:    nSendUserConnectAndAuthenticate
 * Signature: (I[BJ)Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamGameServer_nSendUserConnectAndAuthenticate
  (JNIEnv *, jclass, jint, jbyteArray, jlong);

/*
 * Class:     steam_ISteamGameServer
 * Method:    nSendUserDisconnect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_steam_ISteamGameServer_nSendUserDisconnect
  (JNIEnv *, jclass, jlong);

/*
 * Class:     steam_ISteamGameServer
 * Method:    nBUpdateUserData
 * Signature: (JLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamGameServer_nBUpdateUserData
  (JNIEnv *, jclass, jlong, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
