/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class steam_ISteamUtils_ENotificationPosition */

#ifndef _Included_steam_ISteamUtils_ENotificationPosition
#define _Included_steam_ISteamUtils_ENotificationPosition
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
