/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class steam_steam_gameserver */

#ifndef _Included_steam_steam_gameserver
#define _Included_steam_steam_gameserver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     steam_steam_gameserver
 * Method:    nSteamGameServer_Init
 * Signature: (IIIIIILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_steam_steam_1gameserver_nSteamGameServer_1Init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jstring, jstring);

/*
 * Class:     steam_steam_gameserver
 * Method:    SteamGameServer_Shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_steam_steam_1gameserver_SteamGameServer_1Shutdown
  (JNIEnv *, jclass);

/*
 * Class:     steam_steam_gameserver
 * Method:    SteamGameServer_RunCallbacks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_steam_steam_1gameserver_SteamGameServer_1RunCallbacks
  (JNIEnv *, jclass);

/*
 * Class:     steam_steam_gameserver
 * Method:    SteamGameServer_BSecure
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steam_steam_1gameserver_SteamGameServer_1BSecure
  (JNIEnv *, jclass);

/*
 * Class:     steam_steam_gameserver
 * Method:    SteamGameServer_GetSteamID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_steam_steam_1gameserver_SteamGameServer_1GetSteamID
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
