/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class steam_ISteamRemoteStorage */

#ifndef _Included_steam_ISteamRemoteStorage
#define _Included_steam_ISteamRemoteStorage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     steam_ISteamRemoteStorage
 * Method:    nFileWrite
 * Signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamRemoteStorage_nFileWrite
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     steam_ISteamRemoteStorage
 * Method:    nFileRead
 * Signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_steam_ISteamRemoteStorage_nFileRead
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     steam_ISteamRemoteStorage
 * Method:    nFileForget
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamRemoteStorage_nFileForget
  (JNIEnv *, jclass, jstring);

/*
 * Class:     steam_ISteamRemoteStorage
 * Method:    nFileDelete
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamRemoteStorage_nFileDelete
  (JNIEnv *, jclass, jstring);

/*
 * Class:     steam_ISteamRemoteStorage
 * Method:    nFileExists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamRemoteStorage_nFileExists
  (JNIEnv *, jclass, jstring);

/*
 * Class:     steam_ISteamRemoteStorage
 * Method:    nFilePersisted
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamRemoteStorage_nFilePersisted
  (JNIEnv *, jclass, jstring);

/*
 * Class:     steam_ISteamRemoteStorage
 * Method:    nGetFileSize
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_steam_ISteamRemoteStorage_nGetFileSize
  (JNIEnv *, jclass, jstring);

/*
 * Class:     steam_ISteamRemoteStorage
 * Method:    nGetFileTimestamp
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_steam_ISteamRemoteStorage_nGetFileTimestamp
  (JNIEnv *, jclass, jstring);

/*
 * Class:     steam_ISteamRemoteStorage
 * Method:    nGetQuotaTotalBytes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_steam_ISteamRemoteStorage_nGetQuotaTotalBytes
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamRemoteStorage
 * Method:    nGetQuotaAvailableBytes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_steam_ISteamRemoteStorage_nGetQuotaAvailableBytes
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamRemoteStorage
 * Method:    nIsCloudEnabledForAccount
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamRemoteStorage_nIsCloudEnabledForAccount
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamRemoteStorage
 * Method:    nIsCloudEnabledForApp
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamRemoteStorage_nIsCloudEnabledForApp
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamRemoteStorage
 * Method:    nGetFileCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_steam_ISteamRemoteStorage_nGetFileCount
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamRemoteStorage
 * Method:    nGetFileNameAndSize
 * Signature: (I)Lsteam/SteamFileNameAndSize;
 */
JNIEXPORT jobject JNICALL Java_steam_ISteamRemoteStorage_nGetFileNameAndSize
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
