/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class steam_ISteamUserStats */

#ifndef _Included_steam_ISteamUserStats
#define _Included_steam_ISteamUserStats
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     steam_ISteamUserStats
 * Method:    nRequestCurrentStats
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamUserStats_nRequestCurrentStats
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamUserStats
 * Method:    nStoreStats
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamUserStats_nStoreStats
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamUserStats
 * Method:    nGetAchievement
 * Signature: (Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamUserStats_nGetAchievement
  (JNIEnv *, jclass, jobject);

/*
 * Class:     steam_ISteamUserStats
 * Method:    nSetAchievement
 * Signature: (Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamUserStats_nSetAchievement
  (JNIEnv *, jclass, jobject);

/*
 * Class:     steam_ISteamUserStats
 * Method:    nClearAchievement
 * Signature: (Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamUserStats_nClearAchievement
  (JNIEnv *, jclass, jobject);

/*
 * Class:     steam_ISteamUserStats
 * Method:    nFindLeaderboard
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_steam_ISteamUserStats_nFindLeaderboard
  (JNIEnv *, jclass, jstring);

/*
 * Class:     steam_ISteamUserStats
 * Method:    nFindOrCreateLeaderboard
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_steam_ISteamUserStats_nFindOrCreateLeaderboard
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     steam_ISteamUserStats
 * Method:    nGetLeaderboardName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_steam_ISteamUserStats_nGetLeaderboardName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     steam_ISteamUserStats
 * Method:    nGetLeaderboardEntryCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_steam_ISteamUserStats_nGetLeaderboardEntryCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     steam_ISteamUserStats
 * Method:    nGetLeaderboardSortMethod
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_steam_ISteamUserStats_nGetLeaderboardSortMethod
  (JNIEnv *, jclass, jlong);

/*
 * Class:     steam_ISteamUserStats
 * Method:    nGetLeaderboardDisplayType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_steam_ISteamUserStats_nGetLeaderboardDisplayType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     steam_ISteamUserStats
 * Method:    nDownloadLeaderboardEntries
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_steam_ISteamUserStats_nDownloadLeaderboardEntries
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     steam_ISteamUserStats
 * Method:    nDownloadLeaderboardEntriesForUsers
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_steam_ISteamUserStats_nDownloadLeaderboardEntriesForUsers
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     steam_ISteamUserStats
 * Method:    nGetDownloadedLeaderboardEntry
 * Signature: (JILsteam/LeaderboardEntry_t;Ljava/nio/IntBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamUserStats_nGetDownloadedLeaderboardEntry
  (JNIEnv *, jclass, jlong, jint, jobject, jobject);

/*
 * Class:     steam_ISteamUserStats
 * Method:    nUploadLeaderboardScore
 * Signature: (JIILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_steam_ISteamUserStats_nUploadLeaderboardScore
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     steam_ISteamUserStats
 * Method:    nFindLeaderboardListener
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_steam_ISteamUserStats_nFindLeaderboardListener
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     steam_ISteamUserStats
 * Method:    nFindOrCreateLeaderboardListener
 * Signature: (Ljava/lang/String;IIJ)V
 */
JNIEXPORT void JNICALL Java_steam_ISteamUserStats_nFindOrCreateLeaderboardListener
  (JNIEnv *, jclass, jstring, jint, jint, jlong);

/*
 * Class:     steam_ISteamUserStats
 * Method:    nDownloadLeaderboardEntriesListener
 * Signature: (JIIIJ)V
 */
JNIEXPORT void JNICALL Java_steam_ISteamUserStats_nDownloadLeaderboardEntriesListener
  (JNIEnv *, jclass, jlong, jint, jint, jint, jlong);

/*
 * Class:     steam_ISteamUserStats
 * Method:    nDownloadLeaderboardEntriesForUsersListener
 * Signature: (JJIJ)V
 */
JNIEXPORT void JNICALL Java_steam_ISteamUserStats_nDownloadLeaderboardEntriesForUsersListener
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

/*
 * Class:     steam_ISteamUserStats
 * Method:    nUploadLeaderboardScoreListener
 * Signature: (JIILjava/nio/IntBuffer;J)V
 */
JNIEXPORT void JNICALL Java_steam_ISteamUserStats_nUploadLeaderboardScoreListener
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
