/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class steam_steam_api */

#ifndef _Included_steam_steam_api
#define _Included_steam_steam_api
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     steam_steam_api
 * Method:    nSteamAPI_Init
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_steam_steam_1api_nSteamAPI_1Init
  (JNIEnv *, jclass, jlong);

/*
 * Class:     steam_steam_api
 * Method:    nSteamAPI_Shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_steam_steam_1api_nSteamAPI_1Shutdown
  (JNIEnv *, jclass);

/*
 * Class:     steam_steam_api
 * Method:    nSteamAPI_RunCallbacks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_steam_steam_1api_nSteamAPI_1RunCallbacks
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
