/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class steam_SteamUserStatsListener */

#ifndef _Included_steam_SteamUserStatsListener
#define _Included_steam_SteamUserStatsListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     steam_SteamUserStatsListener
 * Method:    nInitializeCppCallback
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_steam_SteamUserStatsListener_nInitializeCppCallback
  (JNIEnv *, jobject);

/*
 * Class:     steam_SteamUserStatsListener
 * Method:    nFreeCppCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_steam_SteamUserStatsListener_nFreeCppCallback
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
