/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class steam_ISteamUtils */

#ifndef _Included_steam_ISteamUtils
#define _Included_steam_ISteamUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     steam_ISteamUtils
 * Method:    nGetAppID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_steam_ISteamUtils_nGetAppID
  (JNIEnv *, jclass);

/*
 * Class:     steam_ISteamUtils
 * Method:    nSetOverlayNotificationPosition
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_steam_ISteamUtils_nSetOverlayNotificationPosition
  (JNIEnv *, jclass, jint);

/*
 * Class:     steam_ISteamUtils
 * Method:    nGetImageSize
 * Signature: (ILsteam/SteamImageDimensions;)Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamUtils_nGetImageSize
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     steam_ISteamUtils
 * Method:    nGetImageRGBA
 * Signature: (ILjava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_steam_ISteamUtils_nGetImageRGBA
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
